from __future__ import annotations

from typing import Protocol

from app.models.todo import Todo


class TodoRepository(Protocol):
    def list_todos(self) -> list[Todo]: ...
    def create_todo(self, title: str) -> Todo: ...
    def get_todo(self, todo_id: int) -> Todo | None: ...
    def update_todo(self, todo_id: int, *, title: str | None = None, is_completed: bool | None = None) -> Todo | None: ...
    def delete_todo(self, todo_id: int) -> bool: ...
